# Generated by Django 5.0 on 2023-12-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comment_parent_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="parent_comment",
        ),
    ]
